name: MinecraftGPT
version: '${project.version}'
main: nicholas.minecraftgpt.MinecraftGPT
api-version: '1.20'
commands:
  gpt:
    description: Toggle conversation mode with MinecraftGPT
    usage: /gpt
